name: Mirror to Ebrains

on:
  push:
    branches: [ main ]


jobs:
  # set the job name
  to_ebrains:
    runs-on: ubuntu-latest
    steps:

      - name: syncmain
        uses: wei/git-sync@v3

        with:
          source_repo: "PolarBean/DeepSlice"
          source_branch: "main"
          destination_repo: "https://ghpusher:${{ secrets.EBRAINS_GITLAB_ACCESS_TOKEN }}@gitlab.ebrains.eu/polarbean/DeepSlice.git"
          destination_branch: "main"

